@host = http://localhost:8081

###
POST {{host}}/test
Content-Type: application/json

{
   "test":{
      "title": "Epic test title",
      "userID":123,
      "numOfQuestions":2,
      "questions":[
         {
            "question":"to be or not to be?",
            "required": true,
            "answers":[
               {
                  "answer":"yes",
                  "correct":false
               },
               {
                  "answer":"no",
                  "correct":true
               }
            ]
         },
         {
            "question":"1 or 2?",
            "required": false,
            "answers":[
               {
                  "answer":"1",
                  "correct":true
               },
               {
                  "answer":"2",
                  "correct":true
               }
            ]
         }
      ]
   }
}

###
POST {{host}}/test
Content-Type: application/json

{
   "test":{
      "title": "Second test",
      "userID":331,
      "numOfQuestions":5,
      "questions":[
         {
            "question":"Is it good enough??",
            "required": true,
            "answers":[
               {
                  "answer":"si",
                  "correct":false
               },
               {
                  "answer":"nope",
                  "correct":false
               }
            ]
         },
         {
            "question":"oui?",
            "required": false,
            "answers":[
               {
                  "answer":"non",
                  "correct":true
               },
               {
                  "answer":"yup",
                  "correct":true
               }
            ]
         }
      ]
   }
}

###
GET {{host}}/test/7921d2fa-c9d1-45ef-875b-60662e70a1ca
###
GET {{host}}/test/dae86522-3ed3-4589-adbd-3603b74275c2